Repository wecode-bootcamp-korea/21-2nd-Welcome-2-Air-frontend, pull requests merged in 2021-06, with the labels that each got.

#1 [21기 이상훈] Add: folder 구성 및 .vscode 수정
  .vscode/settings.json
  src/Pages/GradeSelect/index.js
  src/Pages/Login/index.js
  src/Pages/Main/index.js
  src/Pages/OrderForm/index.js
Labels: Status: 리뷰 요청

#4 [21기 이상훈] Nav 레이아웃
  public/images/alramIcon.svg
  public/images/cartIcon.svg
  public/images/logo.png
  public/images/searchIcon.svg
  public/images/skyteam_logo.png
  src/Components/Nav/index.js
  src/Routes.js
Labels: Status: Accepted

#6 [21기 오선주] 리뷰 반영 완료
  public/images/appstore.svg
  public/images/facebook.svg
  public/images/googleplay.svg
  public/images/instagram.svg
  public/images/mark1.webp
  public/images/mark2.webp
  public/images/mark3.webp
  public/images/mark4.webp
  public/images/twitter.svg
  public/images/youtube.svg
  src/Components/Footer/Footer.js
  src/Pages/Main/index.js
  src/Routes.js
Labels: Status: 리뷰 요청

#2 [21기 이상훈] 1차 리뷰 반영, 필터 기능 구현
  package-lock.json
  package.json
  public/Datas/fromData.json
  public/Datas/searchInfo.json
  public/Datas/toData.json
  public/Datas/widgetLocation.json
  public/images/calendar.svg
  public/images/calendarIcon.svg
  public/images/class_edge.svg
  public/images/closeBtn.svg
  public/images/closeModal.svg
  public/images/code.svg
  public/images/direction-large.svg
  public/images/downArrow.svg
  public/images/passenger.svg
  public/images/swapIcon.svg
  public/images/widgetChangeBtn.svg
  src/Components/Nav/index.js
  src/Pages/Confirm/index.js
  src/Pages/GradeSelect/index.js
  src/Pages/GradeSelector/Arrival/index.js
  src/Pages/GradeSelector/Departure/index.js
  src/Pages/GradeSelector/FilterSelector/index.js
  src/Pages/GradeSelector/FlightListCard/index.js
  src/Pages/GradeSelector/SearchWidget/Calendar/index.js
  src/Pages/GradeSelector/SearchWidget/CityPicker/index.js
  src/Pages/GradeSelector/SearchWidget/HeadCounter/index.js
  src/Pages/GradeSelector/SearchWidget/index.js
  src/Routes.js
  src/Styles/GlobalStyle.js
  src/Styles/mixin.js
  src/config.js
  src/index.js
  src/utils/fetches.js
Labels: Status: 리뷰 요청

#5 [21기 이기완] ADD 1차 리팩토링 : 리뷰반영
  .eslintrc
  package-lock.json
  package.json
  public/images/login/kakao.png
  public/index.html
  src/Components/Nav/index.js
  src/Pages/Login/Login.js
  src/Routes.js
  src/config.js
Labels: Status: 수정 요청
